version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: test123
      POSTGRES_PASSWORD: test123
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
